version: 0.2

phases:
  pre_build:
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - npm i
  build:
    commands:
    - npm test
  post_build:
    commands:
    - echo "Succeeding? ${CODEBUILD_BUILD_SUCCEEDING}"