version: 0.2



phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - npm i
  build:
    commands:
    - npm test
  post_build:
    commands:
    - echo "Testing and testing this crap"